parameters:
- name: stages
  type: stageList
  default: []

- name: modelRepository
  type: string

resources:
 repositories:
   - repository: A
     name: A
     type: git
   - repository: B
     name: B
     type: git

# variables:
# - template: global-variables.yml
# - template: local-variables.yml@${{ parameters.modelRepository }}

stages:
- ${{ each stage in parameters.stages }}:
  - stage: ${{ stage.stage }}
      # ${{ each spair in s }}:
      # ${{ if notIn(spair.key, 'jobs') }}:
      #   ${{ spair.key }}: ${{ spair.value }}
      # ${{ if eq(spair.key, 'jobs') }}:
    jobs:
      - ${{ each job in stage.jobs }}:
        - job: ${{ j.job }}
              # ${{ each jpair in j }}:
              #   ${{ if notIn(jpair.key, 'steps') }}:
              #     ${{ jpair.key }}: ${{ jpair.value }}
              #   ${{ if eq(jpair.key, 'steps') }}:
          steps:
          - ${{ each step in jobs.steps }}:      
            - ${{ each st in step }}:
                ${{ st.key }}: ${{ st.value }}    
