parameters:
- name: stages
  type: stageList
  default: []

- name: modelRepository
  type: string

resources:
 repositories:
   - repository: A
     name: A
     type: git
   - repository: B
     name: B
     type: git

variables:
- template: global-variables.yml
# - template: local-variables.yml@${{ parameters.modelRepository }}

stages:
- ${{ each stage in parameters.stages }}:
  - stage: ${{ stage.stage }}
    ${{ each pair in stage }}:
      ${{ if notIn(pair.key, 'jobs', 'stage') }}:
        ${{ pair.key }}: ${{ pair.value }}
    jobs:
      - ${{ each job in stage.jobs }}:
        - job: ${{ job.job }}
          ${{ each pair in job }}:
            ${{ if notIn(pair.key, 'steps', 'job') }}:
              ${{ pair.key }}: ${{ pair.value }}
          steps:
          - ${{ each step in job.steps }}:      
            - ${{ each s in step }}:
                ${{ s.key }}: ${{ s.value }}    
